### ISSUE TITLE
Has 100% width with Bootstrap

### ISSUE THREAD

**Issue by aTanCS** [gerardnico/dokuwiki-plugin-minimap#4]
Latest Dokuwiki, Bootstrap3 Template, Mini-map plugin. See screenshot. I gues it should be outside of main div.
![dokuminimap](https://user-images.githubusercontent.com/3854031/40104918-cea0f688-58f1-11e8-8f43-504e53e8b002.png)

**Comment by gerardnico** [comment]
Yes. This is as expected. Normally, the minimap lives in a navigation element. The navigation elemen t constraints the space that the mini-map can take.  In dokuwiki, the navigation element is the sidebar
See: https://www.dokuwiki.org/faq:sidebar

I have also a bootstrap template and I don't have this problem because the sidebar is constraint in width.
For instance: https://gerardnico.com/dokuwiki/dokuwiki

Cheers
Nico

**Comment by gerardnico** [comment]
No reaction closing.
