### ISSUE TITLE
Page titles having colon not suppressed correctly.

### ISSUE THREAD

**Issue by 1nsp1r3rnzt** [gerardnico/dokuwiki-plugin-minimap#7]
I have pages in a directory with common phrase `Introduction to Psychology: Yale: ` in their titles.
For example, `Introduction to Psychology: Yale: Week 2: Languages`.

I have issue suppressing `Introduction to Psychology: Yale: ` 
I used `<minimap suppress="Introduction to Psychology: Yale:">`

The sidebar has `: Yale: Week 2: Languages` as one of the title.
I tried using `\` to escape colon but it gave an empty sidebar.
How can I escape the phrase including  `:Yale: ` from all the titles.

Thanks for your efforts.

**Comment by gerardnico** [comment]
Yes. You are right.

As said in the [doc syntax section](https://github.com/gerardnico/dokuwiki-plugin-minimap/blob/master/README.md#syntax), in the pattern, letters, digits and the following characters are allowed: space, -, _, |, *.

This is due to the parse method to get the suppress pattern at line 49:
https://github.com/gerardnico/dokuwiki-plugin-minimap/blob/master/syntax/minisyntax.php#L49
It's just a basic regular expression and must be improved.

If you change this line with something like that:
`
$attributePattern = "\\s*(\w+)\\s*=\\s*[\'\"]?([\w\d\s-_\|\:\*\.\(\)\?\/\\\\]+)[\'\"]?\\s*";
`
it should work.

**Comment by gerardnico** [comment]
I have changed the way the parsing is done
https://github.com/gerardnico/dokuwiki-plugin-minimap/blob/master/syntax.php#L81

It should work as long as you are not using a ` or " character.
